apiVersion: v1
kind: Service
metadata:
  name: llama32-3b
  labels:
    app: llama32-3b
spec:
  selector:
    app: llama32-3b
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP