apiVersion: apps/v1
kind: Deployment
metadata:
  name: llamastack-deployment
spec:
  template:
    spec:
      volumes:
      # Keep only the volumes we need to update, don't repeat the ones that stay the same
      - name: llama-persist
        persistentVolumeClaim: null # This nullifies the original PVC
        emptyDir: {} # And replaces it with emptyDir
