apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Patches for CI environment
patches:
# Remove the route
- patch: |-
    $patch: delete
    kind: Route
    metadata:
      name: llamastack-server
  target:
    kind: Route
    name: llamastack-server

# Remove the PVC
- patch: |-
    $patch: delete
    kind: PersistentVolumeClaim
    metadata:
      name: llamastack-llama-persist
  target:
    kind: PersistentVolumeClaim
    name: llamastack-llama-persist

# Replace PVC with emptyDir in deployment
- path: deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: llamastack-deployment

# Update configmap for CI
- path: configmap-patch.yaml
  target:
    version: v1
    kind: ConfigMap
    name: llamastack-run-config
